name: coingecko_api
description: Dart package that provides simple access to the CoinGecko API (Version 3)
version: 1.1.0
repository: https://github.com/yegor-pelykh/coingecko_api
issue_tracker: https://github.com/yegor-pelykh/coingecko_api/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  dio: ^4.0.6
  intl: ^0.17.0
