name: coingecko_api
description: Dart package that provides simple access to the CoinGecko API (Version 3)
version: 1.1.1+1
repository: https://github.com/yegor-pelykh/coingecko_api
issue_tracker: https://github.com/yegor-pelykh/coingecko_api/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5

dependencies:
  dio: ^5.4.3+1
  intl: ^0.19.0
